Repository red-hat-storage/kubernetes-csi-addons, pull requests merged in 2022-01, with the labels that each got.

#13 ci: disable dependabot PR creation
  .github/dependabot.yml
Labels: approved, lgtm

#14 sync upstream main branch to downstream
  .github/workflows/build-push.yaml
  .github/workflows/test-build.yaml
  Makefile
  README.md
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manifests/bases/csi-addons.clusterserviceversion.yaml
  docs/ci.md
Labels: approved, lgtm

#16 build: generate a clusterserviceversion manifest with PACKAGE_NAME
  Makefile
  config/manifests/bases/clusterserviceversion.yaml.in
  config/manifests/kustomization.yaml
Labels: approved, lgtm

#18 [DOWNSTREAM-ONLY] Bug 2042997: build: hide the CSI-Addons Operator from the UI
  config/manifests/bases/clusterserviceversion.yaml.in
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#20 sync upstream main branch to downstream
  PROJECT
  api/v1alpha1/reclaimspacejob_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/rbac/role.yaml
  controllers/persistentvolumeclaim_controller.go
  controllers/persistentvolumeclaim_controller_test.go
  controllers/reclaimspacejob_controller.go
  controllers/suite_test.go
  docs/reclaimspace.md
  internal/sidecar/service/reclaimspace.go
  sidecar/main.go
Labels: approved, lgtm

#23 Bug 2046677: controller: add pvc finalizer rbac for annotation controller
  config/rbac/role.yaml
  controllers/persistentvolumeclaim_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#24 Bug 2048370: CSI-Addons controller makes node reclaimspace request even when the PVC is not mounted to any pod
  controllers/reclaimspacejob_controller.go
  controllers/reclaimspacejob_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified
