Repository red-hat-storage/kubernetes-csi-addons, pull requests merged in 2024-09, with the labels that each got.

#189 Syncing latest changes from upstream main for kubernetes-csi-addons
  config/default/kustomization.yaml
  go.mod
  go.sum
  internal/client/fake/volumegroup-client.go
  internal/client/volumegroup-client.go
  internal/client/volumegroup-client_test.go
  internal/proto/generate.go
  internal/proto/volumegroup.pb.go
  internal/proto/volumegroup.proto
  internal/proto/volumegroup_grpc.pb.go
  internal/sidecar/service/volumegroup.go
  sidecar/main.go
  vendor/github.com/csi-addons/spec/lib/go/volumegroup/volumegroup.pb.go
  vendor/github.com/csi-addons/spec/lib/go/volumegroup/volumegroup_grpc.pb.go
  vendor/modules.txt
Labels: approved, lgtm

#191 BUG 2309195: fix pvc reclaimspace & keyrotation annotation filter
  internal/controller/csiaddons/persistentvolumeclaim_controller.go
  internal/sidecar/service/encryptionkeyrotation.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#190 BUG 2309191: deploy: remove extra prefix: csi-addons-
  config/default/kustomization.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified

#193 Syncing latest changes from upstream main for kubernetes-csi-addons
  config/crd/bases/csiaddons.openshift.io_csiaddonsnodes.yaml
  config/crd/bases/csiaddons.openshift.io_encryptionkeyrotationcronjobs.yaml
  config/crd/bases/csiaddons.openshift.io_encryptionkeyrotationjobs.yaml
  config/crd/bases/csiaddons.openshift.io_networkfences.yaml
  config/crd/bases/csiaddons.openshift.io_reclaimspacecronjobs.yaml
  config/crd/bases/csiaddons.openshift.io_reclaimspacejobs.yaml
  config/crd/bases/replication.storage.openshift.io_volumegroupreplicationclasses.yaml
  config/crd/bases/replication.storage.openshift.io_volumegroupreplicationcontents.yaml
  config/crd/bases/replication.storage.openshift.io_volumegroupreplications.yaml
  config/crd/bases/replication.storage.openshift.io_volumereplicationclasses.yaml
  config/crd/bases/replication.storage.openshift.io_volumereplications.yaml
  config/rbac/role.yaml
  deploy/controller/crds.yaml
  deploy/controller/rbac.yaml
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
  tools/vendor/modules.txt
  tools/vendor/sigs.k8s.io/controller-tools/pkg/rbac/parser.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraphmatching.go
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/cmp.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortanyfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/modules.txt
Labels: approved, lgtm

#196 BUG 2311893: replication: add new Validated condition
  internal/controller/replication.storage/status.go
  internal/controller/replication.storage/volumereplication_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#199 Syncing latest changes from upstream main for kubernetes-csi-addons
  internal/controller/csiaddons/persistentvolumeclaim_controller.go
  internal/controller/csiaddons/persistentvolumeclaim_controller_test.go
Labels: approved, lgtm

#200 Syncing latest changes from upstream main for kubernetes-csi-addons
  config/manifests/bases/clusterserviceversion.yaml.in
Labels: approved, lgtm

#201 Syncing latest changes from upstream main for kubernetes-csi-addons
  go.mod
  go.sum
  vendor/k8s.io/api/resource/v1alpha3/generated.pb.go
  vendor/k8s.io/api/resource/v1alpha3/generated.proto
  vendor/k8s.io/api/resource/v1alpha3/types.go
  vendor/k8s.io/api/resource/v1alpha3/types_swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#202 Syncing latest changes from main for kubernetes-csi-addons
  api/replication.storage/v1alpha1/volumereplication_types.go
  config/manifests/bases/clusterserviceversion.yaml.in
  internal/controller/csiaddons/persistentvolumeclaim_controller.go
  internal/controller/csiaddons/persistentvolumeclaim_controller_test.go
  internal/controller/replication.storage/status.go
  internal/controller/replication.storage/volumereplication_controller.go
Labels: approved, lgtm

#203 Syncing latest changes from upstream main for kubernetes-csi-addons
  config/crd/bases/csiaddons.openshift.io_csiaddonsnodes.yaml
  config/crd/bases/csiaddons.openshift.io_encryptionkeyrotationcronjobs.yaml
  config/crd/bases/csiaddons.openshift.io_encryptionkeyrotationjobs.yaml
  config/crd/bases/csiaddons.openshift.io_networkfences.yaml
  config/crd/bases/csiaddons.openshift.io_reclaimspacecronjobs.yaml
  config/crd/bases/csiaddons.openshift.io_reclaimspacejobs.yaml
  config/crd/bases/replication.storage.openshift.io_volumegroupreplicationclasses.yaml
  config/crd/bases/replication.storage.openshift.io_volumegroupreplicationcontents.yaml
  config/crd/bases/replication.storage.openshift.io_volumegroupreplications.yaml
  config/crd/bases/replication.storage.openshift.io_volumereplicationclasses.yaml
  config/crd/bases/replication.storage.openshift.io_volumereplications.yaml
  deploy/controller/crds.yaml
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
  tools/vendor/golang.org/x/sys/unix/ztypes_linux.go
  tools/vendor/golang.org/x/sys/windows/types_windows.go
  tools/vendor/modules.txt
  tools/vendor/sigs.k8s.io/controller-tools/pkg/version/version.go
  tools/vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
  tools/vendor/sigs.k8s.io/controller-tools/pkg/webhook/zz_generated.markerhelp.go
  vendor/google.golang.org/grpc/experimental/stats/metricregistry.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/mem/buffer_slice.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm

#205 Syncing latest changes from upstream main for kubernetes-csi-addons
  cmd/csi-addons/main.go
Labels: approved, lgtm

#207 BUG 2314404: controller/pvc: add checks for nil/empty pvc.Spec.StorageClassName
  internal/controller/csiaddons/persistentvolumeclaim_controller.go
  internal/controller/csiaddons/persistentvolumeclaim_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#208 Syncing latest changes from upstream main for kubernetes-csi-addons
  .github/workflows/build-push.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/kind-deploy.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/test-build.yaml
  .github/workflows/test-golang.yaml
  go.mod
  internal/controller/csiaddons/csiaddonsnode_controller.go
  internal/controller/csiaddons/csiaddonsnode_controller_test.go
Labels: approved, lgtm

#209 Bug 2314454: refactor parseEndpoint to accept pod names with '.' in it
  internal/controller/csiaddons/csiaddonsnode_controller.go
  internal/controller/csiaddons/csiaddonsnode_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
