Repository red-hat-storage/kubernetes-csi-addons, pull requests merged in 2025-04, with the labels that each got.

#277 Syncing latest changes from upstream main for kubernetes-csi-addons
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
  tools/vendor/golang.org/x/oauth2/README.md
  tools/vendor/golang.org/x/oauth2/oauth2.go
  tools/vendor/golang.org/x/oauth2/pkce.go
  tools/vendor/golang.org/x/oauth2/token.go
  tools/vendor/modules.txt
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/oauth2/token.go
  vendor/modules.txt
Labels: approved, lgtm

#281 Syncing latest changes from upstream main for kubernetes-csi-addons
  internal/controller/csiaddons/reclaimspacejob_controller.go
Labels: approved, lgtm

#273 DFBUGS-1953 DFBUGS-1952: rebase: update golang.org/x/net to v0.33 to address CVE-2024-45338
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: approved, lgtm, do-not-merge/hold, jira/valid-reference, jira/valid-bug

#283 DFBUGS-2142: [release-4.19]: fix: avoid panic due to incorrect logger key-value pairs
  internal/controller/csiaddons/reclaimspacejob_controller.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate

#289 Syncing latest changes from upstream main for kubernetes-csi-addons
  go.mod
  go.sum
  vendor/cel.dev/expr/README.md
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/endpointsharding/endpointsharding.go
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/metadata/metadata.go
  vendor/google.golang.org/grpc/internal/transport/client_stream.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/server_stream.go
  vendor/google.golang.org/grpc/resolver/map.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm

#291 Syncing latest changes from upstream main for kubernetes-csi-addons
  internal/controller/replication.storage/volumegroupreplication_controller.go
Labels: approved, lgtm

#292 [release-4.19] DFBUGS-2339: use helper function for label selector in volumegroupreplication
  internal/controller/replication.storage/volumegroupreplication_controller.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug
