Repository red-hat-storage/kubernetes-csi-addons, pull requests merged in 2025-06, with the labels that each got.

#304 Syncing latest changes from upstream main for kubernetes-csi-addons
  api/replication.storage/v1alpha1/volumegroupreplicationcontent_types.go
  api/replication.storage/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/replication.storage.openshift.io_volumegroupreplicationcontents.yaml
  deploy/controller/crds.yaml
  docs/volumegroupreplicationclass.md
  docs/volumegroupreplicationcontent.md
  internal/controller/replication.storage/volumegroupreplication_controller.go
  internal/controller/replication.storage/volumegroupreplicationcontent_controller.go
Labels: approved, lgtm

#306 [release-4.19] DFBUGS-2843: remove namespace name from pvc owner annotation
  internal/controller/replication.storage/pvc_test.go
  internal/controller/replication.storage/volumegroupreplication_controller.go
  internal/controller/replication.storage/volumegroupreplication_test.go
  internal/controller/replication.storage/volumereplication_controller.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug, jira/severity-critical

#308 [release-4.17] DFBUGS-2302: fix: avoid panic due to incorrect logger key-value pairs
  internal/controller/csiaddons/reclaimspacejob_controller.go
  sidecar/internal/csiaddonsnode/csiaddonsnode.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate
