Repository red-hat-storage/kubernetes-csi-addons, pull requests merged in 2025-02, with the labels that each got.

#254 Syncing latest changes from upstream main for kubernetes-csi-addons
  internal/proto/encryptionkeyrotation.pb.go
  internal/proto/networkfence.pb.go
  internal/proto/reclaimspace.pb.go
  internal/proto/replication.pb.go
  internal/proto/volumegroup.pb.go
  tools/go.mod
  tools/go.sum
  tools/vendor/google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo/main.go
  tools/vendor/google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo/reflect.go
  tools/vendor/google.golang.org/protobuf/internal/version/version.go
  tools/vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  tools/vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  tools/vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  tools/vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  tools/vendor/google.golang.org/protobuf/types/known/durationpb/duration.pb.go
  tools/vendor/google.golang.org/protobuf/types/known/emptypb/empty.pb.go
  tools/vendor/google.golang.org/protobuf/types/known/fieldmaskpb/field_mask.pb.go
  tools/vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  tools/vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  tools/vendor/google.golang.org/protobuf/types/known/wrapperspb/wrappers.pb.go
  tools/vendor/google.golang.org/protobuf/types/pluginpb/plugin.pb.go
  tools/vendor/modules.txt
Labels: approved, lgtm

#256 Syncing latest changes from upstream main for kubernetes-csi-addons
  config/crd/bases/csiaddons.openshift.io_csiaddonsnodes.yaml
  config/crd/bases/csiaddons.openshift.io_encryptionkeyrotationcronjobs.yaml
  config/crd/bases/csiaddons.openshift.io_encryptionkeyrotationjobs.yaml
  config/crd/bases/csiaddons.openshift.io_networkfenceclasses.yaml
  config/crd/bases/csiaddons.openshift.io_networkfences.yaml
  config/crd/bases/csiaddons.openshift.io_reclaimspacecronjobs.yaml
  config/crd/bases/csiaddons.openshift.io_reclaimspacejobs.yaml
  config/crd/bases/replication.storage.openshift.io_volumegroupreplicationclasses.yaml
  config/crd/bases/replication.storage.openshift.io_volumegroupreplicationcontents.yaml
  config/crd/bases/replication.storage.openshift.io_volumegroupreplications.yaml
  config/crd/bases/replication.storage.openshift.io_volumereplicationclasses.yaml
  config/crd/bases/replication.storage.openshift.io_volumereplications.yaml
  deploy/controller/crds.yaml
  tools/go.mod
  tools/go.sum
  tools/vendor/github.com/spf13/pflag/.editorconfig
  tools/vendor/github.com/spf13/pflag/.golangci.yaml
  tools/vendor/github.com/spf13/pflag/flag.go
  tools/vendor/github.com/spf13/pflag/ip.go
  tools/vendor/github.com/spf13/pflag/ipnet_slice.go
  tools/vendor/github.com/spf13/pflag/string_array.go
  tools/vendor/k8s.io/api/resource/v1alpha3/generated.proto
  tools/vendor/k8s.io/api/resource/v1alpha3/types.go
  tools/vendor/k8s.io/api/resource/v1alpha3/types_swagger_doc_generated.go
  tools/vendor/k8s.io/api/resource/v1beta1/generated.proto
  tools/vendor/k8s.io/api/resource/v1beta1/types.go
  tools/vendor/k8s.io/api/resource/v1beta1/types_swagger_doc_generated.go
  tools/vendor/modules.txt
  tools/vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/validation.go
  tools/vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/traverse.go
  tools/vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
  tools/vendor/sigs.k8s.io/controller-tools/pkg/webhook/zz_generated.markerhelp.go
Labels: approved, lgtm

#257 Syncing latest changes from upstream main for kubernetes-csi-addons
  internal/proto/encryptionkeyrotation.pb.go
  internal/proto/networkfence.pb.go
  internal/proto/reclaimspace.pb.go
  internal/proto/replication.pb.go
  internal/proto/volumegroup.pb.go
  tools/go.mod
  tools/go.sum
  tools/vendor/google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo/init.go
  tools/vendor/google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo/main.go
  tools/vendor/google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo/opaque.go
  tools/vendor/google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo/reflect.go
  tools/vendor/google.golang.org/protobuf/compiler/protogen/protogen_apilevel.go
  tools/vendor/google.golang.org/protobuf/compiler/protogen/protogen_opaque.go
  tools/vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  tools/vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  tools/vendor/google.golang.org/protobuf/internal/encoding/tag/tag.go
  tools/vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  tools/vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  tools/vendor/google.golang.org/protobuf/internal/filetype/build.go
  tools/vendor/google.golang.org/protobuf/internal/flags/flags.go
  tools/vendor/google.golang.org/protobuf/internal/genid/goname.go
  tools/vendor/google.golang.org/protobuf/internal/impl/codec_field.go
  tools/vendor/google.golang.org/protobuf/internal/impl/codec_message.go
  tools/vendor/google.golang.org/protobuf/internal/impl/codec_message_opaque.go
  tools/vendor/google.golang.org/protobuf/internal/impl/lazy.go
  tools/vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  tools/vendor/google.golang.org/protobuf/internal/impl/message.go
  tools/vendor/google.golang.org/protobuf/internal/impl/message_opaque.go
  tools/vendor/google.golang.org/protobuf/internal/impl/message_reflect.go
  tools/vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  tools/vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  tools/vendor/google.golang.org/protobuf/internal/impl/validate.go
  tools/vendor/google.golang.org/protobuf/internal/impl/weak.go
  tools/vendor/google.golang.org/protobuf/internal/version/version.go
  tools/vendor/google.golang.org/protobuf/proto/decode.go
  tools/vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  tools/vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  tools/vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  tools/vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  tools/vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  tools/vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  tools/vendor/modules.txt
Labels: approved, lgtm

#259 Syncing latest changes from upstream main for kubernetes-csi-addons
  cmd/csi-addons/volumegroup.go
  internal/controller/csiaddons/csiaddonsnode_controller.go
Labels: approved, lgtm

#262 Syncing latest changes from upstream main for kubernetes-csi-addons
  go.mod
  go.sum
  sidecar/internal/csiaddonsnode/csiaddonsnode.go
  sidecar/main.go
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/internal/encoding/tag/tag.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filetype/build.go
  vendor/google.golang.org/protobuf/internal/flags/flags.go
  vendor/google.golang.org/protobuf/internal/genid/goname.go
  vendor/google.golang.org/protobuf/internal/impl/codec_field.go
  vendor/google.golang.org/protobuf/internal/impl/codec_message.go
  vendor/google.golang.org/protobuf/internal/impl/codec_message_opaque.go
  vendor/google.golang.org/protobuf/internal/impl/lazy.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_opaque.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/impl/validate.go
  vendor/google.golang.org/protobuf/internal/impl/weak.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/modules.txt
Labels: approved, lgtm

#261 DFBUGS-848: [release-4.18]: csiaddonsNode: Recreate CSIAddonsNode with active sidecar(s)
  sidecar/internal/csiaddonsnode/csiaddonsnode.go
  sidecar/main.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug, jira/severity-critical

#264 DFBUGS-1261: fix empty volume group creation through cli tool
  cmd/csi-addons/volumegroup.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#236 DFBUGS-850: Reflect cephrbd image health in VR and VRG status
  api/replication.storage/v1alpha1/volumereplication_types.go
  internal/controller/replication.storage/status.go
  internal/controller/replication.storage/volumereplication_controller.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug
