Repository red-hat-storage/kubernetes-csi-addons, pull requests merged in 2025-09, with the labels that each got.

#334 DFBUGS-3845: [release-4.20] remove pvc finalizers only after VGR is ready to be deleted
  internal/controller/replication.storage/finalizers.go
  internal/controller/replication.storage/volumegroupreplication_controller.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug, jira/severity-important

#332 DFBUGS-3935: [DOWNSTREAM ONLY] sidecar: cleanup stale csiaddonsnode owned by DaemonSet
  sidecar/internal/csiaddonsnode/csiaddonsnode.go
  sidecar/main.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#340 Syncing latest changes from upstream main for kubernetes-csi-addons
  internal/proto/encryptionkeyrotation.pb.go
  internal/proto/networkfence.pb.go
  internal/proto/reclaimspace.pb.go
  internal/proto/replication.pb.go
  internal/proto/volumegroup.pb.go
  tools/go.mod
  tools/go.sum
  tools/vendor/google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo/opaque.go
  tools/vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  tools/vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  tools/vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  tools/vendor/google.golang.org/protobuf/internal/filedesc/presence.go
  tools/vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  tools/vendor/google.golang.org/protobuf/internal/impl/codec_message_opaque.go
  tools/vendor/google.golang.org/protobuf/internal/impl/message_opaque.go
  tools/vendor/google.golang.org/protobuf/internal/impl/presence.go
  tools/vendor/google.golang.org/protobuf/internal/version/version.go
  tools/vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  tools/vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  tools/vendor/modules.txt
Labels: approved, lgtm
